language: python

python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - python -m tests.test_momentums -v
  - python -m tests.test_trends -v
  - python -m tests.test_utilities -v
  - python -m tests.test_volatilities -v
  - python -m tests.test_volumes -v

branches:
  only:
    - master
