language: python

python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - py.test --cov-report term --cov=tests/

env:
  - CODECOV_TOKEN

branches:
  only:
    - master
