language: python

python:
  - "3.6"

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - pip install --upgrade pip

install:
  - pip install pipenv

script:
  - python -m tests.test_momentums
  - python -m tests.test_trends
  - python -m tests.test_utilities
  - python -m tests.test_volatilities
  - python -m tests.test_volumes
  - py.test --cov-report term --cov=ttrpy/

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
