language: python

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - pip install --upgrade pip

install: "make"

cache:
  - pip

jobs:
  include:
    - stage: test
      python: '3.5'
      script:
        - make test
    - stage: test
      python: '3.6'
      script:
        - make test
    - stage: test
      python: '3.7'
      dist: xenial
      script:
        - make test
    - stage: coverage
      python: '3.6'
      script:
        - make coverage
